### ISSUE TITLE
No CUDA GPUs are available

### ISSUE THREAD

**Issue by FosRexx** [lyh-18/TCVC-Temporally-Consistent-Video-Colorization#17]
I was trying to run the project but I get `RuntimeError: No CUDA GPUs are available` error, even though I have a CUDA supported GPU. When I run: 
```
python3 test_TCVC_onesampling.py
```
inside `codes` directory, I get this:
```python
(major-project) [anshu@REDACTED codes]$ python3 test_TCVC_onesampling.py
Traceback (most recent call last):
  File "test_TCVC_onesampling.py", line 278, in <module>
    main()
  File "test_TCVC_onesampling.py", line 159, in main
    model = TCVC_IDC_arch.TCVC_IDC(nf=64, N_RBs=3, key_net="sig17", dataset="DAVIS4")
  File "/home/anshu/Projects/major-project/TCVC/codes/models/archs/TCVC_IDC_arch.py", line 99, in __init__
    self.channel_reduction = Channel_Reduction(128, 64).cuda()
  File "/home/anshu/.conda/envs/major-project/lib/python3.8/site-packages/torch/nn/modules/module.py", line 689, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/anshu/.conda/envs/major-project/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/anshu/.conda/envs/major-project/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/home/anshu/.conda/envs/major-project/lib/python3.8/site-packages/torch/nn/modules/module.py", line 689, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/anshu/.conda/envs/major-project/lib/python3.8/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

But in the same environment when I run `torch.cuda.is_available()` or `torch.cuda.get_device_name()`, I get the expected results:
```bash
(major-project) [anshu@REDACTED codes]$ python3 -c "import torch; print(torch.cuda.is_available()); print(torch.cuda.get_device_name());"
True
NVIDIA GeForce RTX 4050 Laptop GPU
```

`nvidia-smi` output:
```bash
(major-project) [anshu@REDACTED codes]$ nvidia-smi
Tue Dec  3 20:44:58 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   36C    P4            590W /   30W |      15MiB /   6141MiB |     19%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A       833      G   /usr/lib/Xorg                                   4MiB |
+-----------------------------------------------------------------------------------------+
```

Conda environment:
```
name: major-project
channels:
  - nvidia
  - nvidia/label/cuda-11.3.0
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.13=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - binutils_impl_linux-64=2.43=h4bf12b8_2
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2024.8.30=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - contourpy=1.1.1=py38h7f3f72f_1
  - cuda=11.3.0=h3b286be_0
  - cuda-command-line-tools=11.3.0=h3b286be_0
  - cuda-compiler=11.3.0=h3b286be_0
  - cuda-cudart=11.3.58=hc1aae59_0
  - cuda-cuobjdump=11.3.58=hc78e225_0
  - cuda-cupti=11.3.58=h9a3dd33_0
  - cuda-cuxxfilt=11.3.58=he670d9e_0
  - cuda-gdb=11.3.58=h531059a_0
  - cuda-libraries=11.3.0=h3b286be_0
  - cuda-libraries-dev=11.3.0=h3b286be_0
  - cuda-memcheck=11.3.58=h8711ecb_0
  - cuda-nvcc=11.3.58=h2467b9f_0
  - cuda-nvdisasm=11.3.58=hd2ea46e_0
  - cuda-nvml-dev=12.4.127=0
  - cuda-nvprof=11.3.58=h860cd9e_0
  - cuda-nvprune=11.3.58=hb917323_0
  - cuda-nvrtc=11.3.58=he300756_0
  - cuda-nvtx=11.3.58=h3fa534a_0
  - cuda-nvvp=11.3.58=hd16380c_0
  - cuda-runtime=11.3.0=h3b286be_0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=11.3.58=h58da6c8_0
  - cuda-thrust=11.3.58=h7b74f08_0
  - cuda-toolkit=11.3.0=h3b286be_0
  - cuda-tools=11.3.0=h3b286be_0
  - cuda-visual-tools=11.3.0=h3b286be_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - cytoolz=0.12.3=py38h01eb140_0
  - dask-core=2023.5.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - double-conversion=3.3.0=h59595ed_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.4=h5888daf_0
  - ffmpeg=6.1.2=gpl_h3e00e3c_103
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py38h2019614_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2024.10.0=pyhff2d567_0
  - gcc=9.5.0=h1fea6ba_13
  - gcc_impl_linux-64=9.5.0=h99780fb_19
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.82.2=h44428e9_0
  - glib-tools=2.82.2=h4833e2c_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - gxx=9.5.0=h1fea6ba_13
  - gxx_impl_linux-64=9.5.0=h99780fb_19
  - harfbuzz=9.0.0=hda332d3_1
  - hdf5=1.14.3=nompi_h2d575fe_107
  - icu=75.1=he02047a_0
  - imagecodecs-lite=2019.12.3=py38he82f83a_8
  - imageio=2.36.0=pyh12aca89_1
  - imath=3.1.12=h7955e40_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipython=8.12.2=pyh41d4057_0
  - jasper=4.2.4=h536e39c_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_1
  - lazy_loader=0.4=pyhd8ed1ab_1
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=20_linux64_openblas
  - libclang-cpp19.1=19.1.4=default_hb5137d0_0
  - libclang13=19.1.4=default_h9c6a7e4_0
  - libcublas=11.4.2.10064=h8a72295_0
  - libcufft=10.4.2.58=h58ccd86_0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.2.4.58=h99380db_0
  - libcurl=8.10.1=hbbe4b11_0
  - libcusolver=11.1.1.58=hec68242_0
  - libcusparse=11.5.0.58=hf5aa513_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=9.5.0=h0a57e50_19
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt=1.11.0=ha770c72_2
  - libgcrypt-devel=1.11.0=hb9d3cd8_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgcrypt-tools=1.11.0=hb9d3cd8_2
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_0
  - libglu=9.0.3=h03adeef_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.51=hbd13f7d_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=20_linux64_openblas
  - liblapacke=3.9.0=20_linux64_openblas
  - libllvm19=19.1.4=ha7bfdaf_1
  - libmpdec=4.0.0=h4bc722e_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=11.3.3.44=h8df316f_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.4=h7f98852_1002
  - libnvjpeg=11.4.1.58=h3d06750_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopencv=4.10.0=qt6_py38h3839c77_603
  - libopenvino=2024.3.0=h2da1b83_0
  - libopenvino-auto-batch-plugin=2024.3.0=hb045406_0
  - libopenvino-auto-plugin=2024.3.0=hb045406_0
  - libopenvino-hetero-plugin=2024.3.0=h5c03a75_0
  - libopenvino-intel-cpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-gpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-npu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-ir-frontend=2024.3.0=h5c03a75_0
  - libopenvino-onnx-frontend=2024.3.0=h07e8aee_0
  - libopenvino-paddle-frontend=2024.3.0=h07e8aee_0
  - libopenvino-pytorch-frontend=2024.3.0=he02047a_0
  - libopenvino-tensorflow-frontend=2024.3.0=h39126c6_0
  - libopenvino-tensorflow-lite-frontend=2024.3.0=he02047a_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=17.2=h04577a9_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libsanitizer=9.5.0=h2f262e1_19
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.47.0=hadc24fc_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=256.7=h2774228_1
  - libtiff=4.7.0=he137b08_1
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.13.5=hb346dea_0
  - libzlib=1.3.1=hb9d3cd8_2
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib=3.7.3=py38h578d9bd_0
  - matplotlib-base=3.7.3=py38h58ed7fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpg123=1.32.9=hc50e24c_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_2
  - mysql-libs=9.0.1=he0572af_2
  - ncurses=6.5=he02047a_1
  - networkx=3.1=pyhd8ed1ab_0
  - ninja=1.12.1=h297d8ca_0
  - nspr=4.36=h5888daf_0
  - nss=3.107=hdf54f9c_0
  - numpy=1.24.4=py38h59b608b_0
  - ocl-icd=2.3.2=hb9d3cd8_2
  - opencl-headers=2024.10.24=h5888daf_0
  - opencv=4.10.0=qt6_py38h994133a_603
  - openexr=3.2.2=h04e0de5_2
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openldap=2.6.9=he970967_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38h2bc05a7_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.43.2=h59595ed_0
  - ply=3.11=pyhd8ed1ab_2
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-opencv=4.10.0=qt6_py38h5776979_603
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.9=py38hffdaa6c_5
  - pyqt5-sip=12.12.2=py38h17151c0_5
  - python=3.8.20=h4a871b0_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.8=5_cp38
  - pywavelets=1.4.1=py38h7f0c24c_1
  - pyyaml=6.0.2=py38h2019614_0
  - qt-main=5.15.15=h796de64_1
  - qt6-main=6.7.3=h6e8976b_1
  - readline=8.2=h8228510_1
  - scikit-image=0.20.0=py38hf403d1e_1
  - scipy=1.9.1=py38hea3f02b_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sip=6.7.12=py38h17151c0_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=2.2.1=h5888daf_0
  - sysroot_linux-64=2.17=h4a8ded7_18
  - tbb=2022.0.0=hceb3a55_0
  - tifffile=2020.6.3=py_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.4.1=py38hfb59056_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py38h01eb140_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_4
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - charset-normalizer==3.4.0
      - idna==3.10
      - requests==2.32.3
      - torch==1.12.1+cu113
      - torchaudio==0.12.1+cu102
      - torchvision==0.13.1+cu113
      - urllib3==2.2.3
```

I am using cuda=11.3.0 from nvidia/lable/cuda-11.3.0 anaconda channel, PyTorch version 1.12.1+cu113.

Also i compiled FlowNet2 with C++ standard 14, since it was the least standard that was supported by PyTorch, but that should not be an issue since it compiled properly.

**Comment by FosRexx** [comment]
Fixed it.
Had to change the number in this line to 0.

https://github.com/lyh-18/TCVC-Temporally-Consistent-Video-Colorization/blob/08cfe3694e1fff9153921eff14f3d22ebd5d900b/codes/test_TCVC_onesampling.py#L136
