### ISSUE TITLE
Missing requirements.txt?

### ISSUE THREAD

**Issue by Divide-By-0** [lyh-18/TCVC-Temporally-Consistent-Video-Colorization#6]
Hey -- I saw you use CUDA 10 in the readme, but would be nice to know the exact versions of cudatoolkit and cudnn, as well as the RAM in the GPU, so I don't run into config issues! A requirements.txt dump of the pip packages would also be equally helpful.

**Comment by taneljairus** [comment]
I have it running on Ubuntu 22.04 with following Anaconda environment (Python 3.8)
[list.txt](https://github.com/lyh-18/TCVC-Temporally-Consistent-Video-Colorization/files/9693164/list.txt)

Hope it helps.

**Comment by Divide-By-0** [comment]
Got it. Can you please publish either an AWS AMI or a Docker container or a `history` dump of how you setup the machine? Does it work with CUDA > 10?

**Comment by Divide-By-0** [comment]
Specifically, once I do `conda install -c hcc cudatoolkit=10.1` and point to that path, I get

```
(base) CUDA_HOME=~/miniconda3/pkgs/cudatoolkit-10.1.243-0 python setup.py develop
No CUDA runtime is found, using CUDA_HOME='/home/ec2-user/miniconda3/pkgs/cudatoolkit-10.1.243-0'
running develop
/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing channelnorm_cuda.egg-info/PKG-INFO
writing dependency_links to channelnorm_cuda.egg-info/dependency_links.txt
writing top-level names to channelnorm_cuda.egg-info/top_level.txt
reading manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
writing manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/home/ec2-user/tcvc-modal/TCVC/codes/models/archs/networks/channelnorm_package/setup.py", line 18, in <module>
    setup(
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 406, in build_extensions
    self._check_cuda_version()
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 782, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/ec2-user/miniconda3/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

**Comment by taneljairus** [comment]
I'm running it on Windows 10 through WSL2. Biggest hurdle was that I had previously installed CUDA from Ubuntu repository and it conflicted with everything. After I followed the CUDA installation instructions from here https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html, things started to work.

Since it's my VM for random stuff, it may have packages that are not needed for this project. So you can probably remove some lines (as the ones mentioned in the inconsistency), as those get installed as prerequisites of others. with suitable versions.

Anyway - here's conda env and pip freeze.
[conda_env.txt](https://github.com/lyh-18/TCVC-Temporally-Consistent-Video-Colorization/files/9712765/conda_env.txt)
[pip-freeze.txt](https://github.com/lyh-18/TCVC-Temporally-Consistent-Video-Colorization/files/9712766/pip-freeze.txt)

**Comment by Divide-By-0** [comment]
Awesome! If you don't mind, it would also be great to get the driver set up for the exact versions you use; I went through that tutorial, but I think my versions were a little bit wrong. So 'g++ --version', 'gcc --version', 'nvcc --version', 'whereis gcc', 'whereis cuda', 'whereis g++' would all be incredible -- it's unclear to me what things are coming from the python package and what things are coming from the machine library, and what exact versions things are.

**Comment by taneljairus** [comment]
Here it is. Apparently I don't have nvcc in path, so I put nvidia-smi also. 

#g++ --version
g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0                

#gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0      

#nvcc --version
Command 'nvcc' not found, but can be installed with:
apt install nvidia-cuda-toolkit 

#nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:42:00.0  On |                  N/A |
|  0%   46C    P8    16W / 200W |    598MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

#whereis gcc
gcc: /usr/bin/gcc /usr/lib/gcc /usr/share/gcc /usr/share/man/man1/gcc.1.gz 

#whereis cuda
cuda: /usr/local/cuda 

whereis g++
g++: /usr/bin/g++ /usr/share/man/man1/g++.1.gz

**Comment by Divide-By-0** [comment]
I am still really struggling to run this on AWS or GCP -- the machine specs are always a little bit off, or my Docker image doesn't compile. You can see what my [setup is right now](https://github.com/Divide-By-0/tcvc-modal/blob/main/main.py) -- any chance you'd have any corrections here or be able to point me to the specific image on AWS/GCP you setup on?
